name: Build Windows
on: [push, workflow_dispatch]
permissions:
  contents: write
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
      - uses: dtolnay/rust-toolchain@stable
      - run: npm ci
      - run: npm run build
      - name: Build
        env:
          PROTOC: ${{ github.workspace }}\.protoc\bin\protoc.exe
        shell: bash
        run: |
          rm -f src-tauri/.cargo/config.toml
          npx tauri build --bundles msi
      - name: Create Release
        run: |
          gh release create v0.10.6 src-tauri/target/release/bundle/msi/*.msi --title "v0.10.6" --notes "App with UI优化+Save弹窗" --target ${{ github.sha }}
        env:
          GH_TOKEN: ${{ github.token }}
